INSERT INTO football_players (name, shirt_number, age, position, is_active) VALUES
    ('Lionel Messi', 10, 36, 'Forward', TRUE),
    ('Cristiano Ronaldo', 7, 39, 'Forward', TRUE),
    ('Kevin De Bruyne', 17, 34, 'Midfielder', TRUE),
    ('Virgil van Dijk', 4, 34, 'Defender', TRUE),
    ('Kylian Mbappé', 7, 27, 'Forward', TRUE),
    ('Erling Haaland', 9, 25, 'Forward', TRUE),
    ('Luka Modrić', 10, 40, 'Midfielder', FALSE),
    ('Neymar Jr.', 11, 33, 'Forward', TRUE),
    ('Joshua Kimmich', 6, 31, 'Midfielder', TRUE),
    ('Alisson Becker', 1, 33, 'Goalkeeper', TRUE),
    ('Trent Alexander-Arnold', 66, 27, 'Defender', TRUE),
    ('Sergio Ramos', 4, 39, 'Defender', FALSE),
    ('Robert Lewandowski', 9, 37, 'Forward', TRUE),
    ('Jan Oblak', 13, 33, 'Goalkeeper', TRUE),
    ('Jude Bellingham', 22, 22, 'Midfielder', TRUE),
    ('Pedri', 8, 23, 'Midfielder', TRUE),
    ('João Cancelo', 27, 31, 'Defender', TRUE),
    ('Harry Kane', 9, 32, 'Forward', TRUE),
    ('Thibaut Courtois', 1, 34, 'Goalkeeper', TRUE),
    ('Achraf Hakimi', 2, 27, 'Defender', TRUE),
    ('Phil Foden', 47, 25, NULL, TRUE),
    ('Marco Verratti', NULL, 33, 'Midfielder', FALSE),
    ('Gerard Piqué', 3, NULL, 'Defender', FALSE),
    ('Ederson Moraes', 31, 32, 'Goalkeeper', TRUE),
    ('Heung-min Son', 7, 33, NULL, TRUE),
    ('Paul Pogba', 6, 32, 'Midfielder', TRUE),
    ('Sadio Mané', 10, NULL, 'Forward', TRUE),
    ('Raphaël Varane', 19, 33, 'Defender', TRUE),
    ('Memphis Depay', NULL, 32, 'Forward', TRUE),
    ('Gianluigi Donnarumma', 99, 27, NULL, TRUE);